"""Shared limits for source-backed module diagram contracts."""

MAX_MODULE_DIAGRAM_POSITION_INTENTS = 4096
MAX_MODULE_DIAGRAM_EDGE_INTENTS = 4096
MAX_MODULE_DIAGRAM_NODE_INTENTS = 1
MAX_FOCUS_TREE_NODE_CREATION_OCCUPIED_PATHS = 65536
