"""
Generate compatibility files and validate repository metadata.

Source of truth:
- requirements.txt
- requirements-dev.txt
- src/paradev/version.py

pyproject.toml reads those files through setuptools dynamic metadata.
scripts/sync-env.bash then refreshes package metadata, lockfiles, and the conda
adapter. The canonical product version also updates desktop package metadata
and the release project-package catalog binding.

Tool priority for installs (highest to lowest):
1. uv        - uv.lock + `uv sync`
2. pip       - requirements*.txt + `pip install -e ".[dev]"`
3. pyproject - `pip install -e ".[dev]"` when only pyproject metadata is available
4. conda     - environment-dev.yml with `-e ".[dev]"`

Usage:
    python scripts/sync-env.py
    python scripts/sync-env.py --check
"""

from __future__ import annotations

import re
import sys
from collections.abc import Callable

from heavenbase.utils import dumps_json, exists_file, get_file_dir, load_txt, loads_json, pj, save_txt

ROOT = pj(get_file_dir(__file__), "..", abs=True)

_SOURCE_REQUIREMENTS = ("requirements.txt", "requirements-dev.txt")
_CONDA_FILE = "environment-dev.yml"
_DESKTOP_PACKAGE_FILE = "apps/desktop/package.json"
_DESKTOP_PACKAGE_LOCK_FILE = "apps/desktop/package-lock.json"
_PROJECT_PACKAGE_CATALOG_FILE = "src/paradev/resources/release/project-packages.json"
_PROJECT_PACKAGE_CATALOG_SCHEMA = "paradev.release.project-package-catalog.v1"
_PARADEV_VERSION_PATTERN = re.compile(
    r"^(?P<core>(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*))" r"(?:(?:\.0+dev(?P<legacy_dev>\d*))|(?:\.dev(?P<pep_dev>\d+)))?$"
)
_CONDA_TEMPLATE = (
    "# Generated by scripts/sync-env.py - do not edit.\n"
    "# Edit requirements*.txt, then run bash scripts/sync-env.bash\n"
    "# Fallback: conda env create -f environment-dev.yml\n"
    "name: {name}-dev\n"
    "channels:\n"
    "  - conda-forge\n"
    "dependencies:\n"
    "  - python={python_ver}\n"
    "  - pip\n"
    "  - pip:\n"
    '    - -e ".[dev]"'
)


def _project_name(pyproject_text: str) -> str:
    match = re.search(r'^name = "([^"]+)"', pyproject_text, re.M)
    if not match:
        raise ValueError("missing [project].name in pyproject.toml")
    return match.group(1)


def _python_pin() -> str:
    path = pj(ROOT, ".python-version")
    if exists_file(path):
        return load_txt(path).strip()
    pyproject_text = load_txt(pj(ROOT, "pyproject.toml"))
    match = re.search(r'requires-python\s*=\s*"([^"]+)"', pyproject_text)
    return match.group(1) if match else "3.12"


def _package_version() -> str:
    version_py = pj(ROOT, "src", "paradev", "version.py")
    match = re.search(r'__version__\s*=\s*"([^"]+)"', load_txt(version_py))
    if not match:
        raise ValueError(f"missing __version__ in {version_py}")
    return match.group(1)


def _desktop_version(package_version: str) -> str:
    match = _PARADEV_VERSION_PATTERN.fullmatch(package_version)
    if not match:
        raise ValueError(
            "src/paradev/version.py must use MAJOR.MINOR.PATCH, " "MAJOR.MINOR.PATCH.devN, or the current " "MAJOR.MINOR.PATCH.000devN development form"
        )
    dev_number = match.group("legacy_dev")
    if dev_number is None:
        dev_number = match.group("pep_dev")
    if dev_number is None and "dev" not in package_version:
        return match.group("core")
    # npm SemVer uses a hyphen before the numeric development identifier.
    return f'{match.group("core")}-{int(dev_number or "0")}'


def _sync_poetry_version(pyproject_text: str, package_version: str) -> str:
    lines: list[str] = []
    in_poetry = False
    replaced = False
    for line in pyproject_text.splitlines():
        if line.strip() == "[tool.poetry]":
            in_poetry = True
        elif line.startswith("[") and in_poetry:
            in_poetry = False
        if in_poetry and line.startswith("version = "):
            line = f'version = "{package_version}"'
            replaced = True
        lines.append(line)
    if not replaced:
        raise ValueError("missing [tool.poetry].version in pyproject.toml")
    return "\n".join(lines) + "\n"


def _sync_desktop_package(text: str, desktop_version: str) -> str:
    payload = loads_json(text)
    if not isinstance(payload, dict) or payload.get("name") != "@paradev/desktop":
        raise ValueError(f"invalid ParaDev desktop package metadata: {_DESKTOP_PACKAGE_FILE}")
    payload["version"] = desktop_version
    return dumps_json(payload, ensure_ascii=False, indent=2) + "\n"


def _sync_desktop_package_lock(text: str, desktop_version: str) -> str:
    payload = loads_json(text)
    if not isinstance(payload, dict) or payload.get("name") != "@paradev/desktop":
        raise ValueError(f"invalid ParaDev desktop lock metadata: {_DESKTOP_PACKAGE_LOCK_FILE}")
    packages = payload.get("packages")
    if not isinstance(packages, dict):
        raise ValueError(f"missing packages table in {_DESKTOP_PACKAGE_LOCK_FILE}")
    root_package = packages.get("")
    if not isinstance(root_package, dict) or root_package.get("name") != "@paradev/desktop":
        raise ValueError(f"missing root desktop package in {_DESKTOP_PACKAGE_LOCK_FILE}")
    payload["version"] = desktop_version
    root_package["version"] = desktop_version
    return dumps_json(payload, ensure_ascii=False, indent=2) + "\n"


def _sync_project_package_catalog(
    text: str,
    package_version: str,
    desktop_version: str,
) -> str:
    payload = loads_json(text)
    if not isinstance(payload, dict) or payload.get("schema") != _PROJECT_PACKAGE_CATALOG_SCHEMA:
        raise ValueError(f"invalid ParaDev project-package catalog: {_PROJECT_PACKAGE_CATALOG_FILE}")
    packages = payload.get("packages")
    if not isinstance(packages, list) or not packages or not all(isinstance(row, dict) for row in packages):
        raise ValueError(f"project-package catalog must contain package rows: {_PROJECT_PACKAGE_CATALOG_FILE}")
    payload["paradev_version"] = package_version
    payload["desktop_version"] = desktop_version
    return dumps_json(payload, ensure_ascii=False, indent=2) + "\n"


def _expected_version_files(pyproject_text: str) -> list[tuple[str, str, str]]:
    package_version = _package_version()
    desktop_version = _desktop_version(package_version)
    generators: tuple[tuple[str, Callable[[str], str]], ...] = (
        (
            _DESKTOP_PACKAGE_FILE,
            lambda text: _sync_desktop_package(text, desktop_version),
        ),
        (
            _DESKTOP_PACKAGE_LOCK_FILE,
            lambda text: _sync_desktop_package_lock(text, desktop_version),
        ),
        (
            _PROJECT_PACKAGE_CATALOG_FILE,
            lambda text: _sync_project_package_catalog(
                text,
                package_version,
                desktop_version,
            ),
        ),
    )
    expected = [
        (
            "pyproject.toml",
            pj(ROOT, "pyproject.toml"),
            _sync_poetry_version(pyproject_text, package_version),
        )
    ]
    expected.extend((label, pj(ROOT, label), generator(load_txt(pj(ROOT, label)))) for label, generator in generators)
    return expected


def _validate_pyproject_wiring(pyproject_text: str) -> None:
    if 'dynamic = ["version", "dependencies", "optional-dependencies"]' not in pyproject_text:
        raise SystemExit("pyproject.toml must declare dynamic version, dependencies, and optional-dependencies")
    if 'dependencies = { file = ["requirements.txt"] }' not in pyproject_text:
        raise SystemExit("pyproject.toml must load runtime deps from requirements.txt")
    if 'optional-dependencies.dev = { file = ["requirements-dev.txt"] }' not in pyproject_text:
        raise SystemExit("pyproject.toml must load dev extras from requirements-dev.txt")
    if re.search(r"^\s*dependencies\s*=\s*\[", pyproject_text, re.M):
        raise SystemExit("pyproject.toml must not inline [project].dependencies; edit requirements.txt")
    if re.search(r"^\s*\[project\.optional-dependencies\]", pyproject_text, re.M):
        raise SystemExit("pyproject.toml must not inline optional-dependencies; edit requirements-*.txt")


def _validate_requirements_sources() -> None:
    missing: list[str] = []
    empty: list[str] = []
    for filename in _SOURCE_REQUIREMENTS:
        path = pj(ROOT, filename)
        if not exists_file(path):
            missing.append(filename)
            continue
        lines = [line.strip() for line in load_txt(path).splitlines() if line.strip() and not line.strip().startswith("#")]
        if not lines:
            empty.append(filename)
    if missing:
        raise SystemExit(f"Missing requirements source file(s): {', '.join(missing)}")
    if empty:
        raise SystemExit(f"Requirements source file(s) have no dependency lines: {', '.join(empty)}")


def _expected_conda(pyproject_text: str) -> str:
    return (
        _CONDA_TEMPLATE.format(
            name=_project_name(pyproject_text),
            python_ver=_python_pin(),
        )
        + "\n"
    )


def generate(check: bool = False) -> None:
    pyproject_path = pj(ROOT, "pyproject.toml")
    pyproject_text = load_txt(pyproject_path)
    _validate_pyproject_wiring(pyproject_text)
    _validate_requirements_sources()
    version_files = _expected_version_files(pyproject_text)
    synced_pyproject = version_files[0][2]
    expected_conda = _expected_conda(synced_pyproject)
    conda_path = pj(ROOT, _CONDA_FILE)
    generated_files = [
        *version_files,
        (_CONDA_FILE, conda_path, expected_conda),
    ]

    if check:
        outdated = [label for label, path, expected in generated_files if not exists_file(path) or load_txt(path) != expected]
        if outdated:
            for label in outdated:
                print(f"Generated metadata out of date: {label}", file=sys.stderr)
            print("Run: bash scripts/sync-env.bash", file=sys.stderr)
            sys.exit(1)
        print("Generated metadata is up to date.")
        return

    for label, path, expected in generated_files:
        if exists_file(path) and load_txt(path) == expected:
            continue
        save_txt(expected.rstrip("\n"), path)
        print(f"  synced {label}")
    print("[sync-env] generated metadata refreshed")


if __name__ == "__main__":
    generate(check="--check" in sys.argv)
